name: Build Abci-Bor
on:
  workflow_dispatch:
   inputs:
    abci-bor-branch:
     description: 'abci-bor branch'
     required: false
     default: 'master'
    abci-bor-version:
     description: 'abci-bor binary version'
     required: false
     default: 'X.Y.Z-beta.U'
    release-on: 
     description: 'public/beta'
     required: false
     default: 'beta'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-18.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo abci-bor-branch ${{github.event.inputs.abci-bor-branch}}
        echo abci-bor-version ${{github.event.inputs.abci-bor-version}}

  build_abci-bor:
    if: ${{github.event.inputs.abci-bor-version != 'X.Y.Z-beta.U'}}
    name: Build abci-bor
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    outputs:
      bor-checksum: ${{steps.bor.outputs.checksum}}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.abci-bor-branch}}
        repository: marlinprotocol/abci-bor
        submodules: recursive
    - name: Make
      run: make bor
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Upload
      id: bor
      run: |
       echo "::set-output name=checksum::$(md5sum build/bin/bor | awk '{print $1;}')"
       aws s3 cp build/bin/bor s3://${{github.event.inputs.release-on}}.artifacts.marlin.pro/projects/abci-bor/${{github.event.inputs.abci-bor-version}}/bor-linux_amd64
 
