name: Build monorepo
on:
  workflow_dispatch:
   inputs:
    revision:
     description: 'oyster-monorepo revision'
     required: false
     default: 'master'
    target:
     description: 'build target'
     required: true
jobs:
  build:
    if: github.actor == 'roshanrags'
    name: Build
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8'
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8-arm'
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: echo
      run: |
        echo revision ${{github.event.inputs.revision}}
    - name: Install Nix
      uses: cachix/install-nix-action@v30
    - name: Cachix
      uses: cachix/cachix-action@v15
      with:
        name: oyster
        authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
    - name: build
      run: nix build -vL --accept-flake-config github:marlinprotocol/oyster-monorepo/${{github.event.inputs.revision}}#${{github.event.inputs.target}}

