name: Build marlinctl
on:
  workflow_dispatch:
   inputs:
    marlinctl-branch:
     description: 'marlinctl branch'
     required: false
     default: 'master'
    marlinctl-version-main:
     description: 'main project version'
     required: true
     default: 'X.Y.Z'
    marlinctl-version-beta:
     description: 'beta version'
     required: true
     default: 'beta.U'
    version-description:
     description: 'description for new version'
     required: false
     default: 'automated'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo marlinctl-branch ${{github.event.inputs.marlinctl-branch}}
        echo marlinctl-version ${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}
        echo version-description ${{github.event.inputs.version-description}}
        
  build_marlinctl:
    name: Build marlinctl
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }} 
    outputs:
      marlinctl-beta-checksum: ${{steps.marlinctl_beta.outputs.checksum}}
      marlinctl-release-checksum: ${{steps.marlinctl_release.outputs.checksum}}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.marlinctl-branch}}
        repository: marlinprotocol/marlinctl2
        submodules: recursive
    - uses: actions/setup-go@v2
    - name: update
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y musl-tools
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Make marlinctl
      id: marlinctl_beta
      if: ${{github.event.inputs.marlinctl-version-main != 'X.Y.Z'}} && ${{github.event.inputs.marlinctl-version-beta != 'beta.U'}}
      run: |
        CC=`which musl-gcc` ./mk.sh ${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}
        echo "::set-output name=checksum::$(md5sum build/marlinctl | awk '{print $1;}')"
        aws s3 cp build/marlinctl s3://beta.artifacts.marlin.pro/projects/marlinctl_beta/${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}/marlinctl-${{matrix.GOOS}}_${{matrix.GOARCH}}
    - name: Make marlinctl_release
      id: marlinctl_release
      if: ${{github.event.inputs.marlinctl-version-main != 'X.Y.Z'}} && ${{github.event.inputs.marlinctl-version-beta != 'beta.U'}}
      run: |
        sh mk.sh ${{github.event.inputs.marlinctl-version-main}}
        echo "::set-output name=checksum::$(md5sum build/marlinctl | awk '{print $1;}')"
        aws s3 cp build/marlinctl s3://beta.artifacts.marlin.pro/projects/marlinctl/${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}/marlinctl-${{matrix.GOOS}}_${{matrix.GOARCH}}
     
  create-pr-marlinctl:
     name: create PR marlinctl
     if: ${{github.event.inputs.marlinctl-version-main != 'X.Y.Z'}} && ${{github.event.inputs.marlinctl-version-beta != 'beta.U'}}
     needs: [build_marlinctl]
     strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
     runs-on: ${{ matrix.os }}
     steps:
     - uses: actions/checkout@v2
       with:
        token: ${{ secrets.PAT }}
        ref: beta
        repository: marlinprotocol/releases
        submodules: recursive
     - name: edit
       run: |
         pip install semantic_version
         python script.py "projects/marlinctl/releases.json" ${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}} "${{github.event.inputs.version-description}}" "${{github.event.inputs.runner-version}}" marlinctl "https://beta.artifacts.marlin.pro/projects/marlinctl_beta/${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}/marlinctl-${{matrix.GOOS}}_${{matrix.GOARCH}}" "${{needs.build_marlinctl.outputs.marlinctl-beta-checksum}}" marlinctl "https://beta.artifacts.marlin.pro/projects/marlinctl/${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}/marlinctl-${{matrix.GOOS}}_${{matrix.GOARCH}}" "${{needs.build_marlinctl.outputs.marlinctl-release-checksum}}"
     - name: pr
       uses: peter-evans/create-pull-request@v3
       with:
          token: ${{ secrets.PAT }}
          branch: auto-marlinctl-${{github.event.inputs.marlinctl-version-main}}-${{github.event.inputs.marlinctl-version-beta}}
          delete-branch: true
          title: 'Update Build'
          
