name: Build control plane
on:
  workflow_dispatch:
   inputs:
    control-plane-version:
     description: 'control plane version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_keygen_linux:
    name: Build keygen linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    outputs:
      control-plane-checksum: ${{steps.control-plane.outputs.checksum}}
    steps:
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }}
    - name: clone
      run: rm -rf control-plane && git clone https://github.com/marlinprotocol/control-plane
    - name: checkout
      run: cd control-plane && git checkout master
    - name: build
      run: cd control-plane && cargo build --release --target ${{ matrix.target }}
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload control-plane
      id: control-plane
#       if: ${{github.event.inputs.control-plane-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum control-plane/target/${{ matrix.target }}/release/control-plane | awk '{print $1;}')"
        aws s3 cp control-plane/target/${{ matrix.target }}/release/control-plane s3://public.artifacts.marlin.pro/projects/enclaves/control-plane_${{github.event.inputs.control-plane-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
