name: Build control plane
on:
  workflow_dispatch:
   inputs:
    control-plane-version:
     description: 'control plane version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo control-plane-version ${{github.event.inputs.control-plane-version}}
  build_control_plane_linux:
    name: Build control plane linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/clang-10
      CXX: /usr/bin/clang++-10
    outputs:
      control-plane-checksum: ${{steps.control-plane.outputs.checksum}}
    steps:
    - name: clone
      run: git clone https://radicle.lsqtech.org/hnrkk4b3996ywswdx9ck1x9op1kqij5s59a8o control-plane
#     - name: checkout
#       run: cd control-plane && git checkout canonical/master
    - name: build
      run: cd control-plane && cargo build --release
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload control-plane
      id: control-plane
#       if: ${{github.event.inputs.control-plane-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum control-plane/target/release/control-plane | awk '{print $1;}')"
        aws s3 cp control-plane/target/release/control-plane s3://public.artifacts.marlin.pro/projects/enclaves/control-plane_${{github.event.inputs.control-plane-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
