name: Build dnsproxy
on:
  workflow_dispatch:
   inputs:
    dnsproxy-version:
     description: 'dnsproxy version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo dnsproxy-version ${{github.event.inputs.dnsproxy-version}}
  build_dnsproxy_linux:
    name: Build dnsproxy linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      dnsproxy-checksum: ${{steps.dnsproxy.outputs.checksum}}
    steps:
    - name: clone
      run: rm -rf dnsproxy && git clone https://github.com/AdguardTeam/dnsproxy
    - name: checkout
      run: cd dnsproxy && git checkout ${{github.events.inputs.dnsproxy-version}}
    - name: golang
      uses: actions/setup-go@v3.3.1
      with:
        go-version: 1.19
    - name: musl
      run: sudo apt install -y musl-tools
    - name: build
      run: cd dnsproxy && CC=`which musl-gcc` go build -mod=vendor -ldflags='-s -w -linkmode external -extldflags "-static"'
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload dnsproxy
      id: dnsproxy
#       if: ${{github.event.inputs.dnsproxy-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum dnsproxy/dnsproxy | awk '{print $1;}')"
        upx dnsproxy/dnsproxy
        aws s3 cp dnsproxy/dnsproxy s3://public.artifacts.marlin.pro/projects/enclaves/dnsproxy_${{github.event.inputs.dnsproxy-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
