name: Build keygen-ed25519
on:
  workflow_dispatch:
   inputs:
    keygen-ed25519-version:
     description: 'keygen-ed25519 version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_keygen-ed25519_linux:
    name: Build keygen-ed25519 linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      keygen-ed25519-checksum: ${{steps.keygen-ed25519.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo keygen-ed25519-version ${{github.event.inputs.keygen-ed25519-version}}
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }} && sudo apt-get install -y musl-tools
    - name: clone
      run: rm -rf keygen-ed25519 && git clone https://github.com/marlinprotocol/keygen keygen-ed25519
    - name: checkout
      run: cd keygen-ed25519 && git checkout master
    - name: build
      run: cd keygen-ed25519 && CC=musl-gcc cargo build --release --target ${{ matrix.target }} --bin keygen-ed25519
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload keygen-ed25519
      id: keygen-ed25519
#       if: ${{github.event.inputs.keygen-ed25519-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum keygen-ed25519/target/${{ matrix.target }}/release/keygen-ed25519 | awk '{print $1;}')"
        upx keygen-ed25519/target/${{ matrix.target }}/release/keygen-ed25519
        aws s3 cp keygen-ed25519/target/${{ matrix.target }}/release/keygen-ed25519 s3://public.artifacts.marlin.pro/projects/enclaves/keygen-ed25519_${{github.event.inputs.keygen-ed25519-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
