name: Build keygen
on:
  workflow_dispatch:
   inputs:
    keygen-version:
     description: 'keygen version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_keygen_linux:
    name: Build keygen linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      keygen-checksum: ${{steps.keygen.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo keygen-version ${{github.event.inputs.keygen-version}}
    - name: dependencies for libsodium
      run: sudo apt-get install clang
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }}
    - name: clone
      run: rm -rf keygen && git clone https://github.com/marlinprotocol/keygen
    - name: checkout
      run: cd keygen && git checkout master
    - name: build
      run: cd keygen && cargo build --release --target ${{ matrix.target }}
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload keygen
      id: keygen
#       if: ${{github.event.inputs.keygen-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum keygen/target/${{ matrix.target }}/release/keygen | awk '{print $1;}')"
        upx keygen/target/${{ matrix.target }}/release/keygen
        aws s3 cp keygen/target/${{ matrix.target }}/release/keygen s3://public.artifacts.marlin.pro/projects/enclaves/keygen_${{github.event.inputs.keygen-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
