name: Build nitro-log-stream
on:
  workflow_dispatch:
   inputs:
    nitro-log-stream-version:
     description: 'nitro-log-stream version'
#      required: false
     default: 'vX.Y.Z-beta.U'
jobs:
  build_linux:
    name: Build nitro-log-stream linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          rust-image: 'ed7795c6eaccae53be35939e883e8c3de0197b21e8eddbd9f04b0c4bc757c094'
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8-arm'
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          rust-image: 'c428882ff081342a9661fb13a1d059ecdc0b6e979ffec64b80371cf20a2088b0'
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      nitro-log-stream-checksum: ${{steps.nitro-log-stream.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo nitro-log-stream-version ${{github.event.inputs.nitro-log-stream-version}}
    - name: clone
      run: rm -rf nitro-log-stream && git clone https://github.com/marlinprotocol/nitro-log-stream
    - name: checkout
      run: cd nitro-log-stream && git checkout master
    - name: build
      run: cd nitro-log-stream && sudo docker run --rm -v `pwd`:/code rust@sha256:${{matrix.rust-image}} /code/build-${{matrix.GOARCH}}.sh
    - name: upload nitro-log-stream
      id: nitro-log-stream
      if: ${{github.event.inputs.nitro-log-stream-version != 'vX.Y.Z-beta.U'}}
      run: |
        AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 cp --endpoint-url ${{secrets.AWS_S3_ENDPOINT}} nitro-log-stream/target/${{ matrix.target }}/release/control-plane s3://artifacts/oyster/binaries/control-plane_${{github.event.inputs.nitro-log-stream-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}