name: Build attestation server
on:
  workflow_dispatch:
   inputs:
    attestation-server-version:
     description: 'attestation server version'
#      required: false
     default: 'vX.Y.Z-beta.U'
jobs:
  build_linux:
    name: Build linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          rust-image: 'ed7795c6eaccae53be35939e883e8c3de0197b21e8eddbd9f04b0c4bc757c094'
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-2-arm'
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          rust-image: 'c428882ff081342a9661fb13a1d059ecdc0b6e979ffec64b80371cf20a2088b0'
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      attestation-server-checksum: ${{steps.attestation-server.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo attestation-server-version ${{github.event.inputs.attestation-server-version}}
    - name: clone
      run: rm -rf oyster-attestation-server && git clone https://github.com/marlinprotocol/oyster-attestation-server oyster-attestation-server
    - name: checkout
      run: cd oyster-attestation-server && git checkout master
    - name: build
      run: cd oyster-attestation-server && sudo docker run --rm -v `pwd`:/code rust@sha256:${{matrix.rust-image}} /code/build-${{matrix.GOARCH}}.sh
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upx
      run: |
        wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-${{matrix.GOARCH}}_linux.tar.xz -O upx.txz
        mkdir -p upx && tar -xvf upx.txz --strip-components=1 -C upx
        sudo mv upx/upx /usr/local/bin/
    - name: upload attestation-server
      id: attestation-server
#       if: ${{github.event.inputs.attestation-server-version != 'vX.Y.Z-beta.U'}}
      run: |
        sudo upx oyster-attestation-server/target/${{ matrix.target }}/release/oyster-attestation-server
        echo "::set-output name=checksum::$(sha256sum oyster-attestation-server/target/${{ matrix.target }}/release/oyster-attestation-server | awk '{print $1;}')"
        aws s3 cp oyster-attestation-server/target/${{ matrix.target }}/release/oyster-attestation-server s3://public.artifacts.marlin.pro/projects/enclaves/attestation-server_${{github.event.inputs.attestation-server-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
