name: Build oyster-utility
on:
  workflow_dispatch:
   inputs:
    oyster-utility-version:
     description: 'oyster-utility version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_oyster_attestation_verifier_linux:
    name: Build oyster-utility linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      oyster-utility-checksum: ${{steps.oyster-utility.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo oyster-utility-version ${{github.event.inputs.oyster-utility-version}}
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }} && sudo apt-get install -y musl-tools
    - name: clone
      run: rm -rf oyster-utility && git clone https://github.com/marlinprotocol/oyster-utility
    - name: checkout
      run: cd oyster-utility && git checkout master
    - name: build
      run: cd oyster-utility && CC=musl-gcc cargo build --release --target ${{ matrix.target }}
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload oyster-utility
      id: oyster-utility
#       if: ${{github.event.inputs.oyster-utility-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum oyster-utility/target/${{ matrix.target }}/release/oyster-utility | awk '{print $1;}')"
        upx oyster-utility/target/${{ matrix.target }}/release/oyster-utility
        aws s3 cp oyster-utility/target/${{ matrix.target }}/release/oyster-utility s3://public.artifacts.marlin.pro/projects/enclaves/oyster-utility_${{github.event.inputs.oyster-utility-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
