name: Build oyster-attestation-verifier
on:
  workflow_dispatch:
   inputs:
    oyster-attestation-verifier-version:
     description: 'oyster-attestation-verifier version'
#      required: false
     default: 'vX.Y.Z-beta.U'
jobs:
  build_oyster_attestation_verifier_linux:
    name: Build oyster-attestation-verifier linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          rust-image: 'ed7795c6eaccae53be35939e883e8c3de0197b21e8eddbd9f04b0c4bc757c094'
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-2-arm'
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          rust-image: 'c428882ff081342a9661fb13a1d059ecdc0b6e979ffec64b80371cf20a2088b0'
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      oyster-attestation-verifier-checksum: ${{steps.oyster-attestation-verifier.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo oyster-attestation-verifier-version ${{github.event.inputs.oyster-attestation-verifier-version}}
    - name: clone
      run: rm -rf oyster-attestation-verifier && git clone https://github.com/marlinprotocol/oyster-attestation-verifier
    - name: checkout
      run: cd oyster-attestation-verifier && git checkout master
    - name: build
      run: cd oyster-attestation-verifier && sudo docker run --rm -v `pwd`:/code rust@sha256:${{matrix.rust-image}} /code/build-${{matrix.GOARCH}}.sh
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upx
      run: |
        wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-${{matrix.GOARCH}}_linux.tar.xz -O upx.txz
        mkdir -p upx && tar -xvf upx.txz --strip-components=1 -C upx
        sudo mv upx/upx /usr/local/bin/
    - name: upload oyster-attestation-verifier
      id: oyster-attestation-verifier
      if: ${{github.event.inputs.oyster-attestation-verifier-version != 'vX.Y.Z-beta.U'}}
      run: |
        sudo upx oyster-attestation-verifier/target/${{ matrix.target }}/release/oyster-attestation-verifier
        echo "::set-output name=checksum::$(sha256sum oyster-attestation-verifier/target/${{ matrix.target }}/release/oyster-attestation-verifier | awk '{print $1;}')"
        aws s3 cp oyster-attestation-verifier/target/${{ matrix.target }}/release/oyster-attestation-verifier s3://public.artifacts.marlin.pro/projects/enclaves/attestation-verifier_${{github.event.inputs.oyster-attestation-verifier-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
