name: Build oyster-init-server
on:
  workflow_dispatch:
   inputs:
    oyster-init-server-version:
     description: 'oyster-init-server version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_oyster-init-server_linux:
    name: Build oyster-init-server linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      oyster-init-server-checksum: ${{steps.oyster-init-server.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo oyster-init-server-version ${{github.event.inputs.oyster-init-server-version}}
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }} && sudo apt-get install -y musl-tools
    - name: clone
      run: rm -rf oyster-init-server && git clone https://github.com/marlinprotocol/oyster-init-server
    - name: checkout
      run: cd oyster-init-server && git checkout master
    - name: build
      run: cd oyster-init-server && CC=musl-gcc cargo build --release --target ${{ matrix.target }}
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload oyster-init-server
      id: oyster-init-server
#       if: ${{github.event.inputs.oyster-init-server-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum oyster-init-server/target/${{ matrix.target }}/release/oyster-init-server | awk '{print $1;}')"
        upx oyster-init-server/target/${{ matrix.target }}/release/oyster-init-server
        aws s3 cp oyster-init-server/target/${{ matrix.target }}/release/oyster-init-server s3://public.artifacts.marlin.pro/projects/enclaves/oyster-init-server_${{github.event.inputs.oyster-init-server-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}












