name: Build oyster-attestation-verifier-enclave
on:
  workflow_dispatch:
   inputs:
    oyster-attestation-verifier-enclave-version:
     description: 'oyster-attestation-verifier-enclave version'
#      required: false
     default: 'vX.Y.Z-beta.U'
jobs:
  build_oyster_attestation_verifier_linux:
    name: Build oyster-attestation-verifier-enclave linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-2-arm'
          build_type: Release
          GOOS: linux
          GOARCH: arm64
    runs-on: ${{ matrix.runs-on }}
    outputs:
      oyster-attestation-verifier-enclave-checksum: ${{steps.oyster-attestation-verifier-enclave.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo oyster-attestation-verifier-enclave-version ${{github.event.inputs.oyster-attestation-verifier-enclave-version}}
    - name: clone
      run: rm -rf oyster-attestation-verifier-enclave && git clone https://github.com/marlinprotocol/oyster-attestation-verifier-enclave
    - name: checkout
      run: cd oyster-attestation-verifier-enclave && git checkout master
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - name: build
      run: cd oyster-attestation-verifier-enclave && nix build --out-link result-${{matrix.GOARCH}} ./${{matrix.GOARCH}} -vL --extra-experimental-features "nix-command flakes"
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload oyster-attestation-verifier-enclave
      id: oyster-attestation-verifier-enclave
      if: ${{github.event.inputs.oyster-attestation-verifier-enclave-version != 'vX.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(sha256sum oyster-attestation-verifier-enclave/result-${{matrix.GOARCH}}/image.eif | awk '{print $1;}')"
        aws s3 cp oyster-attestation-verifier-enclave/result-${{matrix.GOARCH}}/image.eif s3://public.artifacts.marlin.pro/eifs/attestation-verifier_${{github.event.inputs.oyster-attestation-verifier-enclave-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}.eif
        aws s3 cp oyster-attestation-verifier-enclave/result-${{matrix.GOARCH}}/pcr.json s3://public.artifacts.marlin.pro/eifs/attestation-verifier_${{github.event.inputs.oyster-attestation-verifier-enclave-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}.json
