name: Build oyster-keygen
on:
  workflow_dispatch:
   inputs:
    oyster-keygen-version:
     description: 'oyster-keygen version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_oyster_keygen_linux:
    name: Build oyster-keygen linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      oyster-keygen-checksum: ${{steps.oyster-keygen.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo oyster-keygen-version ${{github.event.inputs.oyster-keygen-version}}
    - name: setup rust
      run: rustup update && rustup target add ${{ matrix.target }} && sudo apt-get install -y musl-tools
    - name: clone
      run: rm -rf oyster-keygen && git clone https://github.com/marlinprotocol/oyster-keygen
    - name: checkout
      run: cd oyster-keygen && git checkout master
    - name: build
      run: cd oyster-keygen && CC=musl-gcc cargo build --release --target ${{ matrix.target }}
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload oyster-keygen
      id: oyster-keygen
#       if: ${{github.event.inputs.oyster-keygen-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum oyster-keygen/target/${{ matrix.target }}/release/oyster-keygen | awk '{print $1;}')"
        upx oyster-keygen/target/${{ matrix.target }}/release/oyster-keygen
        aws s3 cp oyster-keygen/target/${{ matrix.target }}/release/oyster-keygen s3://public.artifacts.marlin.pro/projects/enclaves/oyster-keygen_${{github.event.inputs.oyster-keygen-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
