name: Build proxies
on:
  workflow_dispatch:
   inputs:
    iptv-version:
     description: 'ip to vsock binary version'
     required: false
     default: 'X.Y.Z-beta.U'
    vtip-version:
     description: 'vsock to ip binary version'
     required: false
     default: 'X.Y.Z-beta.U'
    iptvt-version:
     description: 'ip to vsock transparent binary version'
     required: false
     default: 'X.Y.Z-beta.U'
    vtipt-version:
     description: 'vsock to ip transparent binary version'
     required: false
     default: 'X.Y.Z-beta.U'
    version-description:
     description: 'description for new version'
     required: false
     default: 'automated'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo iptv-version ${{github.event.inputs.iptv-version}}
        echo vtip-version ${{github.event.inputs.vtip-version}}
        echo iptvt-version ${{github.event.inputs.iptvt-version}}
        echo vtipt-version ${{github.event.inputs.vtipt-version}}
        echo version-description ${{github.event.inputs.version-description}}
        
  build_proxies_linux:
    name: Build proxies linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/clang-10
      CXX: /usr/bin/clang++-10
    outputs:
      iptv-checksum: ${{steps.iptv.outputs.checksum}}
      vtip-checksum: ${{steps.vtip.outputs.checksum}}
      iptvt-checksum: ${{steps.iptvt.outputs.checksum}}
      vtipt-checksum: ${{steps.vtipt.outputs.checksum}}
    steps:
    - name: clone
      run: git clone -c remote.origin.fetch=refs/remotes/hyyuaeud98fr3dc6n9uaxstpwkj7yasrcskmfdnk6w1intdxbxujxe/heads/*:refs/remotes/cabbage/* https://radicle.lsqtech.org/hnrkqsu1gmf1quzq3ypjrsau9czaorwnn44zo proxy
    - name: checkout
      run: cd proxy && git checkout cabbage/master
    - name: build
      run: cd proxy && cargo build --release
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload iptv
      id: iptv
      if: ${{github.event.inputs.iptv-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum proxy/target/release/ip-to-vsock | awk '{print $1;}')"
        aws s3 cp proxy/target/release/ip-to-vsock s3://public.artifacts.marlin.pro/projects/enclaves/ip-to-vsock_${{github.event.inputs.iptv-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
    - name: upload vtip
      id: vtip
      if: ${{github.event.inputs.vtip-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum proxy/target/release/vsock-to-ip | awk '{print $1;}')"
        aws s3 cp proxy/target/release/vsock-to-ip s3://public.artifacts.marlin.pro/projects/enclaves/vsock-to-ip_${{github.event.inputs.vtip-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
    - name: upload iptvt
      id: iptvt
      if: ${{github.event.inputs.iptvt-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum proxy/target/release/ip-to-vsock-transparent | awk '{print $1;}')"
        aws s3 cp proxy/target/release/ip-to-vsock-transparent s3://public.artifacts.marlin.pro/projects/enclaves/ip-to-vsock-transparent_${{github.event.inputs.iptvt-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
    - name: upload vtipt
      id: vtipt
      if: ${{github.event.inputs.vtipt-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum proxy/target/release/vsock-to-ip-transparent | awk '{print $1;}')"
        aws s3 cp proxy/target/release/vsock-to-ip-transparent s3://public.artifacts.marlin.pro/projects/enclaves/vsock-to-ip-transparent_${{github.event.inputs.vtipt-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
