name: Release operator/control-plane
on:
  workflow_dispatch:
   inputs:
    version:
     description: 'release version'
     required: true
jobs:
  build:
    if: github.actor == 'roshanrags'
    name: Release
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8'
          OS: linux
          ARCH: amd64
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8-arm'
          OS: linux
          ARCH: arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: echo
      run: |
        echo revision ${{github.event.inputs.revision}}
    - name: Install Nix
      uses: cachix/install-nix-action@v30
    - name: Cachix
      uses: cachix/cachix-action@v15
      with:
        name: oyster
        authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
    - name: build
      run: nix build -vL --accept-flake-config github:marlinprotocol/oyster-monorepo/control-plane-${{github.event.inputs.version}}#musl.operator.control-plane.uncompressed
    - name: upload
      run: AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 cp --endpoint-url ${{secrets.AWS_S3_ENDPOINT}} ./result/bin/control-plane s3://artifacts/oyster/binaries/control-plane_${{github.event.inputs.version}}_${{matrix.OS}}_${{matrix.ARCH}}
