name: Release workerd
on:
  workflow_dispatch:
   inputs:
    version:
     description: 'release version'
     required: true
jobs:
  build:
    if: github.actor == 'roshanrags'
    name: Release
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-8'
          OOS: linux
          ARCH: amd64
        # - os: 'ubuntu-24.04'
        #   runs-on: 'ubicloud-standard-8-arm'
        #   OOS: linux
        #   ARCH: arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: clone
      run: rm -rf workerd && git clone https://github.com/cloudflare/workerd
    - name: checkout
      run: cd workerd && git checkout ${{github.events.inputs.version}}
    - name: build
      run: cd workerd && bazel build --config=thin-lto //src/workerd/server:workerd
    - name: upload
      run: AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 cp --endpoint-url ${{secrets.AWS_S3_ENDPOINT}} workerd/bazel-bin/src/workerd/server/workerd s3://artifacts/oyster/binaries/workerd_${{github.event.inputs.version}}_${{matrix.OOS}}_${{matrix.ARCH}}
