name: Release
on:
  workflow_dispatch:
   inputs:
    project-name:
     description: 'project name'
     required: false
     default: 'nil'
    project-version:
     description: 'project version'
     required: false
     default: 'nil'
jobs: 
  release_binaries:
    name: Make Binary public
    strategy:
      matrix:
        include:
        - os: 'ubuntu-18.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: copy binary
      if: ${{github.event.inputs.project-name != 'nil' && github.event.inputs.project-version != 'nil'}}
      run: |
        aws s3 cp s3://beta.artifacts.marlin.pro/projects/${{github.event.inputs.project-name}}/${{github.event.inputs.project-version}}/* s3://public.artifacts.marlin.pro/projects/${{github.event.inputs.project-name}}/${{github.event.inputs.project-version}}/
