name: Build supervisor
on:
  workflow_dispatch:
   inputs:
    supervisord-version:
     description: 'supervisord version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  build_supervisord_linux:
    name: Build supervisord linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-22.04'
          runs-on: 'ubuntu-22.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-22.04'
          runs-on: self-hosted
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      supervisord-checksum: ${{steps.supervisord.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo supervisord-version ${{github.event.inputs.supervisord-version}}
    - name: clone
      run: rm -rf supervisord && git clone https://github.com/ochinchina/supervisord
    - name: checkout
      run: cd supervisord && git checkout ${{github.events.inputs.supervisord-version}}
    - name: golang
      uses: actions/setup-go@v3.3.1
      with:
        go-version: 1.19
    - name: musl
      run: sudo apt install -y musl-tools
    - name: build
      run: cd supervisord && go generate && CC=`which musl-gcc` go build -tags release -a -ldflags " -s -w -linkmode external -extldflags -static" -o supervisord
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload supervisord
      id: supervisord
#       if: ${{github.event.inputs.supervisord-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum supervisord/supervisord | awk '{print $1;}')"
        upx supervisord/supervisord
        aws s3 cp supervisord/supervisord s3://public.artifacts.marlin.pro/projects/enclaves/supervisord_${{github.event.inputs.supervisord-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
