name: Build supervisor
on:
  workflow_dispatch:
   inputs:
    supervisord-version:
     description: 'supervisord version'
#      required: false
#      default: 'X.Y.Z-beta.U'
jobs:
  echo_input:
    name: display input params
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo
      run: |
        echo supervisord-version ${{github.event.inputs.supervisord-version}}
  build_supervisord_linux:
    name: Build supervisord linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-20.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/clang-10
      CXX: /usr/bin/clang++-10
    outputs:
      supervisord-checksum: ${{steps.supervisord.outputs.checksum}}
    steps:
    - name: clone
      run: git clone https://github.com/ochinchina/supervisord
    - name: checkout
      run: cd supervisord && git checkout ${{github.events.inputs.supervisord-version}}
    - name: build
      run: cd supervisord && go generate && go build -tags release -a -ldflags "-linkmode external -extldflags -static" -o supervisord
    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: upload supervisord
      id: supervisord
#       if: ${{github.event.inputs.supervisord-version != 'X.Y.Z-beta.U'}}
      run: |
        echo "::set-output name=checksum::$(md5sum supervisord/supervisord | awk '{print $1;}')"
        aws s3 cp supervisord/supervisord s3://public.artifacts.marlin.pro/projects/enclaves/supervisord_${{github.event.inputs.supervisord-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
