name: Build supervisor
on:
  workflow_dispatch:
   inputs:
    supervisord-version:
     description: 'supervisord version'
#      required: false
     default: 'vX.Y.Z-beta.U'
jobs:
  build_linux:
    name: Build linux
    strategy:
      matrix:
        include:
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
          golang-image: '02ba164d64e0aee92ab808526e450dea546b5c59ee7d400d1c04c03c126cb59f'
          target: x86_64-unknown-linux-musl
        - os: 'ubuntu-24.04'
          runs-on: 'ubicloud-standard-2-arm'
          build_type: Release
          GOOS: linux
          GOARCH: arm64
          golang-image: 'b2b1734fc70c4c5119b4e257fc558495bcd72e25b95c7ef2918eb705d9779211'
          target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.runs-on }}
    outputs:
      supervisord-checksum: ${{steps.supervisord.outputs.checksum}}
    steps:
    - name: echo
      run: |
        echo supervisord-version ${{github.event.inputs.supervisord-version}}
    - name: clone
      run: rm -rf supervisord && git clone https://github.com/ochinchina/supervisord
    - name: checkout
      run: cd supervisord && git checkout ${{github.event.inputs.supervisord-version}}
    - name: download build script
      run: cd supervisord && wget https://raw.githubusercontent.com/marlinprotocol/release-pipeline/master/supervisord-${{matrix.GOARCH}}.sh -O build-${{matrix.GOARCH}}.sh && chmod +x build-${{matrix.GOARCH}}.sh
    - name: build
      run: cd supervisord && sudo docker run --rm -v `pwd`:/code golang@sha256:${{matrix.golang-image}} /code/build-${{matrix.GOARCH}}.sh
    - name: upx
      run: |
        wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-${{matrix.GOARCH}}_linux.tar.xz -O upx.txz
        mkdir -p upx && tar -xvf upx.txz --strip-components=1 -C upx
        sudo mv upx/upx /usr/local/bin/
    - name: upload supervisord
      id: supervisord
#       if: ${{github.event.inputs.supervisord-version != 'vX.Y.Z-beta.U'}}
      run: |
        sudo upx supervisord/supervisord
        echo "::set-output name=checksum::$(sha256sum supervisord/supervisord | awk '{print $1;}')"
        AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 cp --endpoint-url ${{secrets.AWS_S3_ENDPOINT}} supervisord/supervisord s3://artifacts/oyster/binaries/supervisord_${{github.event.inputs.supervisord-version}}_${{matrix.GOOS}}_${{matrix.GOARCH}}
